---
- block:
  - name: Read the gossip encryption key
    shell:
      cmd: "cat /etc/consul.d/consul.hcl | grep encrypt | awk '{print $3}' | sed 's/\"//g'"
    register: encrypt_string_read
    run_once: true

  - name: Save the gossip encryption key
    set_fact:
      encrypt: "{{ encrypt_string_read.stdout }}"
    when: encrypt_string_read.stdout != ""
  when: encrypt is not defined 
