---
- name: Install Consul
  include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Delete default config file
  file:
    path: /etc/consul.d/consul.hcl
    state: absent
  when: install_consul.changed
