---
- name: Expose advertise_addr
  set_fact:
    advertise_addr: "{{ advertise_addr }}"

- name: Install Consul
  include_tasks: install.yml

- name: Setting the gossip encryption key
  include_tasks: gossip_encryption.yml

- name: Consigure agent config
  include_tasks: client.yml

- name: Configure server config
  include_tasks: server.yml

- name: Configure Consul services
  include_tasks: services.yml
  tags: services
