# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    start_ip = 11
    (1..6).each do |i|
        config.vm.define "consul#{i}" do |c|
            c.vm.box = "centos/8"
            c.vm.hostname = "consul#{i}"
            c.vm.network "private_network", ip: "192.168.101.#{start_ip + i - 1}", name: "vboxnet0"
            c.vm.provider "virtualbox" do |vb|
                vb.memory = 2048
                vb.cpus = 1
                vb.customize ["modifyvm", :id, "--audiocontroller", "sb16"]
            end
            c.vm.provision "file", source: "key.pub", destination: "~/.ssh/me.pub"
            c.vm.provision "shell", inline: <<-SHELL
            cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
            SHELL
        end
    end
end
  