---
- name: Add the HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add Hashicorp repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com "{{ ansible_distribution_release }}" main

- name: Install a specific version Consul
  apt:
    name: consul={{ version }}
  when: version is defined
  notify: Enable and start Consul

- name: Install Consul
  apt:
    name: consul
    update_cache: yes
  when: version is not defined
  notify: Enable and start Consul
  register: install_consul
