---
- name: Install Consul
  include_tasks: install.yml

- name: Setting the gossip encryption key
  include_tasks: gossip_encryption.yml

- name: Setting the gossip encryption key
  include_tasks: client.yml

- name: Setting the gossip encryption key
  include_tasks: server.yml
