---
- name: Consul server configuration
  template:
    src: server.hcl.j2
    dest: /etc/consul.d/server.hcl
    owner: consul
    group: consul
    mode: '0640'
  when: inventory_hostname in groups['servers']
  notify: Restart Consul agent
